version: "3"

networks:
  frontend:
  backend:

services:
  redis:
    image: redis
    networks:
      - backend
    container_name: my-redis
    privileged: true
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ../redis/data:/data
      - ../redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:ro

  mysql:
    image: mysql
    networks:
      - backend
    container_name: my-db
    volumes:
      - ../mysql/config/my.cnf:/etc/mysql/my.cnf:ro
      - ../mysql/data:/var/lib/mysql
      - ../mysql/logs:/usr/local/mysql/log
    environment:
      - MYSQL_ROOT_PASSWORD=666666
    ports:
      - 3306:3306

  phpfpm:
    build: ./phpfpm
    networks:
      - frontend
      - backend
    container_name: my-phpfpm
    volumes:
      - ../phpfpm/php.ini:/usr/local/etc/php/php.ini:ro
      - ../phpfpm/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ../phpfpm/php-fpm.d:/usr/local/etc/php-fpm.d:ro
      - ../phpfpm/crontab:/etc/crontab:ro
      - ../phpfpm/logs/error.log:/usr/local/php/log/error.log
      - ../websits:/websites
    depends_on:
      - redis
      - mysql

  nginx:
    image: nginx
    networks:
      - frontend
    container_name: my-nginx
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/conf.d:/etc/nginx/conf.d:ro
      - ../websits:/websites
    depends_on:
      - phpfpm
    ports:
      - "80:80"
      - "433:433"

